name: build

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      
      - run: |
          npm install
          npm run build
          cd public
          git init
          git remote add origin "{{ github.repositoryUrl }}"
          git config user.email "actions@github.com"
          git conifg user.name "GitHub Actions"
          git add .
          git commit -m "GitHub Pages" --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git branch gh-pages
          header=$(echo -n "ad-m:${GH_TOKEN}" | base64)
          git -c http.extraheader="AUTHORIZATION: basic $header" push --force -u origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
